apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-configmap
  namespace: kube-system
  labels:
    app: mysql
data:
  master.cnf: |
    [mysqld]
    log-bin
  slave.cnf: |
    [mysqld]
    super-read-only
