apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: kube-system
  labels:
    app: mysql
spec:
  ports:
  - name: mysql
    port: 3306
  clusterIP: None
  selector:
    app: mysql

---

apiVersion: v1
kind: Service
metadata:
  name: mysql-read
  namespace: kube-system
  labels:
    app: mysql
spec:
  ports:
  - name: mysql
    port: 3306
  selector:
    app: mysql
