apiVersion: apps/v1
kind: Deployment
metadata:
  name: apollo-admin-deploy
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apollo-admin
  template:
    metadata:
      labels:
        app: apollo-admin
    spec:
      containers:
      - name: apollo-admin
        image: entropypool/apollo-adminservice:1.9.1
        ports:
        - containerPort: 8090
          name: httpport
        resources:
          limits:
            cpu: 200m
            memory: 512Mi
          requests:
            cpu: 50m 
            memory: 128Mi
        env:
          - name: ENV_ENVIRONMENT_TARGET
            valueFrom:
              configMapKeyRef:
                name: system-environment
                key: environment.target
          - name: ENV_CONSUL_HOST
            valueFrom:
              configMapKeyRef:
                name: system-environment
                key: environment.consul_host
          - name: ENV_CONSUL_PORT
            valueFrom:
              configMapKeyRef:
                name: system-environment
                key: environment.consul_port
          - name: ENV_CLUSTER_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-password-secret
                key: rootpassword
      volumes:
      - name: config-volume
        configMap:
          name: apollo-admin-configmap

---
apiVersion: v1 
kind: Service
metadata:
  name: apollo-admin-svc
  namespace: kube-system
  labels:
    app: apollo-admin-svc 
spec:
  selector:
    app: apollo-admin
  type: NodePort
  ports:
  - name: http
    port: 8090
    targetPort: 8090
    protocol: TCP
    nodePort: 30090
